 #GitHub Action Part-1 - Basic
 #Copyleft (c) Vasiliy Zhuravlev 2022.
 
 name: My-GitHubActions-Basic

on:
  push:
	branches:
		- master	
		
jobs:
  my_testing:
	runs-on: ubuntu-latest
	
	steps:
    - name: Print Hello Message	
	  run: echo "Hello World! from testing job"

  my_deploy:
    runs-on: ubuntu-latest
	
    steps:
    - name: Print Hello Message	
      run: echo "Hello World! from deploy job"	
